baseurl = "http://geri.life"
title = "GeriLife®"
theme = "dimension"
languageCode = "fi-fi"
defaultContentLanguage = "fi"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = 'GeriLife® is an open-source tool designed to increase wellbeing.'
  logo = "fa-heartbeat"
  copyright = "2017"
  footer = "test"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/GeriLife/wellbeing"

[languages]
[languages.fi]
languageName = "Suomi"
weight = 1
title = "GeriLife®"
description = 'GeriLife® on avoimen lähdekoodin työkalu ikäihmisten hyvän elämän edistämiseksi.'

[languages.en]
languageName = "English"
weight = 2
